# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provision "shell" do |s|
        s.inline = "sudo rm /tmp/hosts.sh; wget --no-check-certificate -P /tmp https://github.com/waue0920/nchc_vagrant/raw/master/util_tool/hosts.sh; bash /tmp/hosts.sh ; "
    end


config.vm.define :master do |master_config|
    master_config.vm.box = "package.box"
    master_config.vm.hostname = "master"
    master_config.vm.network "private_network", ip: "192.168.33.10"
    master_config.vm.provider "virtualbox" do |v|
	  v.memory = 1024
	  v.cpus = 2
    end

end

config.vm.define :slave do |slave_config|
    slave_config.vm.box = "package.box"
    slave_config.vm.hostname = "slave"
    slave_config.vm.network "private_network", ip: "192.168.33.11"
    slave_config.vm.provider "virtualbox" do |v|
	  v.memory = 1024
	  v.cpus = 2
    end
end

end
