# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
  { 
    :hostname => "hadoop-master",    
    :box => 'ubuntu/trusty64',
    :ip => '192.168.33.10', 
    :ram => 1536,
    :cpus => 2
  },
  { 
    :hostname => "hadoop-slave",
    :box => 'ubuntu/trusty64',
    :ip => '192.168.33.11',
    :ram => 1536,
    :cpus => 2 
  }
]

Vagrant.configure(2) do |config|

    # Install Oracle JDK 8
    config.vm.provision "shell" do |s|
        s.inline = "sudo rm /tmp/equip_java8.sh; wget --no-check-certificate -P /tmp https://github.com/waue0920/nchc_vagrant/raw/master/util_tool/install_java8.sh; sudo bash /tmp/install_java8.sh ; "
    end

    # add user hadoop (PW: hadoop) with sudo permission
    config.vm.provision "shell" do |s|
        s.inline = "sudo rm /tmp/equip_sudo_users.sh; wget --no-check-certificate -P /tmp https://github.com/waue0920/nchc_vagrant/raw/master/util_tool/equip_sudo_users.sh; sudo bash /tmp/equip_sudo_users.sh hadoop hadoop;"
    end

    
    # Download hadoop tarball
    config.vm.provision "shell" do |s|
        s.inline = "wget -P /opt http://archive-primary.cloudera.com/cdh5/cdh/5/hadoop-2.6.0-cdh5.7.0.tar.gz"
    end

    # configure shared folder
    config.vm.synced_folder './share_dir', '/vagrant', disabled: false, 
      # owner: "hadoop", group: "hadoop"

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.host_name = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.name = machine[:hostname]
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpus]]
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            end
        end
    end
end
